stages:
  - build
  - test
  - deploy

linux:build:
  stage: build
  script: echo "Building linux..."

linux:rspec:
  stage: test
  script: echo "Running rspec on linux..."

test_job2:
  stage: test
  script:
    - echo "Testing..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying..."
